name: .NET Framework CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore ./GitActionsTester.sln
    - name: Build project
      run: dotnet build ./GitActionsTester.sln --no-restore
    # Optional test step if there are tests defined in your project
    # - name: Run tests
    #   run: dotnet test ./MyProject/MyProject.sln --no-build --verbosity normal
